spring:
  application:
    name: MyWeb
  datasource:
    url: jdbc:mariadb://localhost:3306/testdb
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

server:
  port: 80

logging:
  level:
    root: info